LR with priors initial implementation
outbrain/outrank pull request #66
Opened 2024-03-12 14:13 UTC by bmramor

2024-03-19 06:10 UTC, SkBlaz reviewed
:partying_face:

2024-03-19 06:10 UTC, SkBlaz commented on outrank/algorithms/importance_estimator.py
> -    if surrogate_model == 'surrogate-LR':
These if-elses could be abstracted away into a modelfactory that returns initialized class w.r.t. str. input

2024-03-19 06:10 UTC, SkBlaz commented on outrank/algorithms/importance_estimator.py
> +    # if counts[0] < len(unique_values) * (2**5):
Let's remove such comments

2024-03-19 06:10 UTC, SkBlaz commented on outrank/algorithms/importance_estimator.py
> +        X = np.concatenate((X,vector_first.reshape(-1, 1)), axis=1)
There is a space missing after `X`, wondering why lint didn't catch that. @miha-jenko maybe some idea?

2024-03-19 06:10 UTC, SkBlaz commented on outrank/algorithms/importance_estimator.py
> +            clf, X, vector_second, scoring='neg_log_loss', cv=4,
Let's put the num. of folds to top of the file as a constant for now

2024-03-19 06:10 UTC, SkBlaz commented on outrank/core_ranking.py
> +    if 'prior' in args.heuristic:
you check for `-prior` at some point, but `prior` at some other point. Consider creating a helper function `is_prior_heuristic` or something, that unifies this behavior (and centralizes it)

2024-03-22 09:52 UTC, bmramor commented on outrank/core_ranking.py
> +    #combinations = prior_combinations_sample(combinations, args)
I am turning this feature off, since there is currently a bug in the interaction with line 216. I propose that we handle this separately.

2024-03-22 10:00 UTC, SkBlaz requested changes

2024-03-22 10:00 UTC, SkBlaz commented on outrank/core_utils.py
> +def is_prior_heuristic(args: Any):
missing return type

2024-04-02 15:09 UTC, SkBlaz approved these changes

2024-04-03 07:56 UTC, merged